# Generated by Django 4.0 on 2024-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('type', models.IntegerField(choices=[(1, 'client'), (2, 'admin'), (3, 'more')], default=1)),
            ],
        ),
    ]
